### ISSUE TITLE
Error in reverseimagesearch with NaN values in RandomForestClassifier

### ISSUE THREAD

**Issue by TPGamesNL** [TUe-CSRP-SEC-2023-2024/zdp-server#5]
```
2024-02-06 22:36:29,514  [/home/teun/phishing/zdp-server/utils/reverseimagesearch.py:53]  INFO: Search mode: image
2024-02-06 22:36:30,567  [/home/teun/phishing/zdp-server/utils/reverseimagesearch.py:69]  INFO: Regions found: 21
2024-02-06 22:36:31,020  [/home/teun/phishing/zdp-server/utils/reverseimagesearch.py:82]  ERROR: Input X contains NaN.
RandomForestClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
Traceback (most recent call last):
  File "/home/teun/phishing/zdp-server/utils/reverseimagesearch.py", line 76, in search_image_all
    logo_prob = self.clf_logo.predict_proba([[w, h, region[2], region[3], region[4], region[5], region[8], region[9], region[10], region[11], region[12], region[13], region[14], region[15]]])[:, 1][0]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/sklearn/model_selection/_search.py", line 522, in predict_proba
    return self.best_estimator_.predict_proba(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 862, in predict_proba
    X = self._validate_X_predict(X)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 602, in _validate_X_predict
    X = self._validate_data(X, dtype=DTYPE, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py", line 921, in check_array
    _assert_all_finite(
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
RandomForestClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
```

**Comment by TPGamesNL** [comment]
in regiondetection.py function `_findregions`, `skew` and `kurtosis` (from scipy stats calculated with the greyscale version of region) return NaN  when all values are equal in the region (i.e. all pixels map to same grayscale color)

**Comment by TPGamesNL** [comment]
https://github.com/TUe-CSRP-SEC-2023-2024/zdp-server/blob/d0e59cfff2b9fff9051dc113e8918229d47c15ac/utils/regiondetection.py#L154-L155

requires some experimentation for the best solution:
e.g., impute values with some default (e.g. 0), or giving a fixed result (e.g., no logo)

**Comment by TPGamesNL** [comment]
one way to solve this is (probably) to upgrade sklearn (scikit-learn) to 1.4.0, due to https://scikit-learn.org/dev/whats_new/v1.4.html#sklearn-ensemble: `ensemble.RandomForestClassifier and ensemble.RandomForestRegressor support missing values [...]`
However, problem is that the classifier is stored with joblib (which uses the pickle library), i.e. object serialization. sklearn isn't made to support serialized objects after version changes (why would it), so the existing classifier file cannot be used. this means we'll need to re-train the classifier for it to work.

we want to avoid these kind of issues in the future, so we should look into better ways to handle model persistence, especially over library updates. see https://scikit-learn.org/stable/model_persistence.html

**Comment by TPGamesNL** [comment]
news flash, main issue lies elsewhere:
https://github.com/TUe-CSRP-SEC-2023-2024/zdp-server/blob/d0e59cfff2b9fff9051dc113e8918229d47c15ac/utils/regiondetection.py#L138

if x or y are smaller than the margin, this will make the indices negative, and in Python negative indices loop back around to the end of the list, so it would instead refer to a completely different portion of the image. this new region was not selected for any particular reason, and it happened to have only the same color on the example image, causing this problem. fixed by not making the margin overflow the indices


since the issue with serialization from above still remains, I will open a new issue for that (this one is polluted enough with my comments as-is)
