### ISSUE TITLE
add check to extension for non-null uuid (causes 500 on backend, escalates to error in extension due to invalid json)

### ISSUE THREAD

**Issue by TPGamesNL** [TUe-CSRP-SEC-2023-2024/zdp-server#7]

**Comment by TPGamesNL** [comment]
```
2024-02-07 11:19:34,929  [/home/teun/phishing/zdp-server/api.py:100]  WARNING: Time elapsed for https://www.paypal.com/signin is 0.0007646083831787109, found in cache with result inconclusive
127.0.0.1 - - [07/Feb/2024 11:19:34] "POST /api/v1/url HTTP/1.1" 200 -
[2024-02-07 11:23:12,571] ERROR in app: Exception on /api/v1/url [POST]
Traceback (most recent call last):
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/api.py", line 77, in check_url
    uuid = json["uuid"]
           ~~~~^^^^^^^^
KeyError: 'uuid'
127.0.0.1 - - [07/Feb/2024 11:23:12] "POST /api/v1/url HTTP/1.1" 500 -
[2024-02-07 11:23:12,829] ERROR in app: Exception on /api/v1/url [POST]
Traceback (most recent call last):
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teun/phishing/zdp-server/api.py", line 77, in check_url
    uuid = json["uuid"]
           ~~~~^^^^^^^^
KeyError: 'uuid'
127.0.0.1 - - [07/Feb/2024 11:23:12] "POST /api/v1/url HTTP/1.1" 500 -
```

error on backend, because uuid from frontend is null / undefined
